const CHANGE_VALUE = 'CHANGE_VALUE';
const FETCH_STATES = 'FETCH_STATES';
const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
const CHANGE_STATE = 'CHANGE_STATE';
const CALCULATE = 'CALCULATE';

export default {
	CHANGE_VALUE,
	FETCH_STATES,
	FETCH_STATES_SUCCESS,
	CHANGE_STATE,
	CALCULATE,
};
